module ApplicationHelper
  def us_states
    [
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY']
    ]
  end

  def country_list
   ["UNITED STATES",
   "AUSTRALIA",
   "CANADA",
   "FRANCE",
   "GREAT BRITAIN AND NORTHERN IRELAND",
   "JAPAN",
   "MEXICO",
   "NEW ZEALAND",
   "AFGHANISTAN",
   "ALAND ISLAND",
   "ALBANIA",
   "ALGERIA",
   "ANDORRA",
   "ANGOLA",
   "ANGUILLA",
   "ANTIGUA AND BARBUDA",
   "ARGENTINA",
   "ARMENIA",
   "ARUBA",
   "AUSTRIA",
   "AZERBAIJAN",
   "BAHAMAS",
   "BAHRAIN",
   "BANGLADESH",
   "BARBADOS",
   "BELARUS",
   "BELGIUM",
   "BELIZE",
   "BENIN",
   "BERMUDA",
   "BHUTAN",
   "BOLIVIA",
   "BOSNIA-HERZEGOVINA",
   "BOTSWANA",
   "BRAZIL",
   "BRITISH VIRGIN ISLANDS",
   "BRUNEI DARUSSALAM",
   "BULGARIA",
   "BURKINA FASO",
   "BURMA",
   "BURUNDI",
   "CAMBODIA",
   "CAMEROON",
   "CAPE VERDE",
   "CAYMAN ISLANDS",
   "CENTRAL AFRICAN REPUBLIC",
   "CHAD",
   "CHILE",
   "CHINA",
   "CHRISTMAS ISLANDS",
   "COCOS ISLAND",
   "COLOMBIA",
   "COMOROS",
   "CONGO (BRAZZAVILLE), REPUBLIC OF THE",
   "CONGO, DEMOCRATIC REPUBLIC OF THE",
   "COOK ISLANDS",
   "COSTA RICA",
   "COTE D IVOIRE",
   "CROATIA",
   "CUBA",
   "CURACAO",
   "CYPRUS",
   "CZECH REPUBLIC",
   "DENMARK",
   "DJIBOUTI",
   "DOMINICA",
   "DOMINICAN REPUBLIC",
   "EAST TIMOR",
   "ECUADOR",
   "EGYPT",
   "EL SALVADOR",
   "EQUATORIAL GUINEA",
   "ERITREA",
   "ESTONIA",
   "ETHIOPIA",
   "FALKLAND ISLANDS",
   "FAROE ISLANDS",
   "FIJI",
   "FINLAND",
   "FRENCH GUIANA",
   "FRENCH POLYNESIA",
   "GABON",
   "GAMBIA",
   "GEORGIA, REPUBLIC OF",
   "GERMANY",
   "GHANA",
   "GIBRALTAR",
   "GREECE",
   "GREENLAND",
   "GRENADA",
   "GUADELOUPE",
   "GUATEMALA",
   "GUERNSEY",
   "GUINEA",
   "GUINEA-BISSAU",
   "GUYANA",
   "HAITI",
   "HONDURAS",
   "HONG KONG",
   "HUNGARY",
   "ICELAND",
   "INDIA",
   "INDONESIA",
   "IRAN",
   "IRAQ",
   "IRELAND",
   "ISLE OF MAN",
   "ISRAEL",
   "ITALY",
   "JAMAICA",
   "JERSEY",
   "JORDAN",
   "KAZAKHSTAN",
   "KENYA",
   "KIRIBATI",
   "KOREA, DEMOCRATIC PEOPLES REPUBLIC OF(NORTH KOREA)",
   "KOREA, REPUBLIC OF (SOUTH KOREA)",
   "KOSOVO, REPUBLIC OF",
   "KUWAIT",
   "KYRGYZSTAN",
   "LAOS",
   "LATVIA",
   "LEBANON",
   "LESOTHO",
   "LIBERIA",
   "LIBYA",
   "LIECHTENSTEIN",
   "LITHUANIA",
   "LUXEMBOURG",
   "MACAO",
   "MACEDONIA, REPUBLIC OF",
   "MADAGASCAR",
   "MALAWI",
   "MALAYSIA",
   "MALDIVES",
   "MALI",
   "MALTA",
   "MARTINIQUE",
   "MAURITANIA",
   "MAURITIUS",
   "MAYOTTE",
   "MOLDOVA",
   "MONACO",
   "MONGOLIA",
   "MONTENEGRO, REPUBLIC OF",
   "MONTSERRAT",
   "MOROCCO",
   "MOZAMBIQUE",
   "NAMIBIA",
   "NAURU",
   "NEPAL",
   "NETHERLANDS",
   "NEW CALEDONIA",
   "NICARAGUA",
   "NIGER",
   "NIGERIA",
   "NIUE",
   "NORFOLK ISLAND",
   "NORWAY",
   "OMAN",
   "PAKISTAN",
   "PANAMA",
   "PAPUA NEW GUINEA",
   "PARAGUAY",
   "PERU",
   "PHILIPPINES",
   "PITCAIRN ISLAND",
   "POLAND",
   "PORTUGAL",
   "QATAR",
   "REUNION",
   "ROMANIA",
   "RUSSIA",
   "RWANDA",
   "SAINT BARTHELEMY",
   "SAINT CHRISTOPHER (ST. KITTS) AND NEVIS",
   "SAINT HELENA",
   "SAINT LUCIA",
   "SAINT MARTIN",
   "SAINT PIERRE AND MIQUELON",
   "SAINT VINCENT AND THE GRENADINES",
   "SAN MARINO",
   "SAO TOME AND PRINCIPE",
   "SAUDI ARABIA",
   "SENEGAL",
   "SERBIA, REPUBLIC OF",
   "SEYCHELLES",
   "SIERRA LEONE",
   "SINGAPORE",
   "SAINT MAARTEN",
   "SLOVAK REPUBLIC",
   "SLOVENIA",
   "SOLOMON ISLANDS",
   "SOMALIA",
   "SOUTH AFRICA",
   "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
   "SPAIN",
   "SRI LANKA",
   "SUDAN",
   "SURINAME",
   "SWAZILAND",
   "SWEDEN",
   "SWITZERLAND",
   "SYRIAN ARAB REPUBLIC",
   "TAIWAN",
   "TAJIKISTAN",
   "TANZANIA",
   "THAILAND",
   "TOGO",
   "TOKELAU GROUP",
   "TONGA",
   "TRINIDAD AND TOBAGO",
   "TUNISIA",
   "TURKEY",
   "TURKMENISTAN",
   "TURKS AND CAICOS ISLANDS",
   "TUVALU",
   "UGANDA",
   "UKRAINE",
   "UNITED ARAB EMIRATES",
   "URUGUAY",
   "UZBEKISTAN",
   "VANUATU",
   "VATICAN CITY",
   "VENEZUELA",
   "VIETNAM",
   "WALLIS AND FUTUNA ISLANDS",
   "WESTERN SAMOA",
   "YEMEN",
   "ZAMBIA",
   "ZIMBABWE"]
  end
end
